### ISSUE TITLE
재생 목록을 재생하면 재생이 되지 않는 에러

### ISSUE THREAD

**Issue by cotwo0139** [cotwo0139/CHINOBOT_BETA#33]
[ERROR] [Shard 0] TypeError: Cannot read property 'title' of undefined
at AudioUtils.formatTrack (/home/ubuntu/Desktop/ChinobotRw/modules/audio/AudioUtils.js:24:55)
at Command.addQueue (/home/ubuntu/Desktop/ChinobotRw/commands/audio/play.js:103:85)     0|RewriteBOT  |     at process._tickCallback (internal/process/next_tick.js:68:7)

![image](https://user-images.githubusercontent.com/40298015/74301492-9183f980-4d96-11ea-950e-554bebbd35a4.png)

**Comment by cotwo0139** [comment]
Fixed Commit: b3bc86422c45eef1e15c64b0ef0d9886795b2a13
