### ISSUE TITLE
TypeError: member.roles.has is not a function

### ISSUE THREAD

**Issue by cotwo0139** [cotwo0139/CHINOBOT_BETA#40]
UnHandledRejection: TypeError: member.roles.has is not a function, Promise: [object Promise]
[08:17:44] [ERROR] TypeError: member.roles.has is not a function
    at Object.filter (/home/ubuntu/Desktop/ChinobotRw/permissions.js:9:86)
    at PermissionChecker.getUserPermission (/home/ubuntu/Desktop/ChinobotRw/modules/utils/perMissionChecker.js:34:16)
    at Event.handleCommand (/home/ubuntu/Desktop/ChinobotRw/events/message.js:36:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by cotwo0139** [comment]
Fixed
